language: perl
os:
  - linux
  - osx
  - windows
    #- PVER=5.28.0 ARGS='--debug --thread -Accflags="-fsanitize=address -g -O2" -Aldflags="-fsanitize=address -g -O2"'
    #- PVER=5.28.0 ARGS='--thread -Accflags="-fsanitize=address -g -O2" -Aldflags="-fsanitize=address -g -O2"'
addons:
  homebrew:
    packages:
    - cpanminus

matrix:
    include:
      - language: perl
        os:
          - linux
          - osx
        env:
          - ASAN_OPTIONS='halt_on_error=0:detect_leaks=0' PVER=5.28.0 ARGS='--thread -Accflags=-fsanitize=address -Accflags=-g -Accflags=-O2 -Aldflags=-fsanitize=address -Aldflags=-g -Aldflags=-O2'
        before_install:
          - \curl -L https://install.perlbrew.pl | bash
          - source ~/perl5/perlbrew/etc/bashrc
          - ( sleep 10; tail -f ~/perl5/perlbrew/build.*.log ) &
          - perlbrew install -j 4 --notest --noman $ARGS $PVER | ~/perl5/perlbrew/build.*.log
          - perlbrew switch $PVER
          - perl -V
        script:
          - perl Makefile.PL verbose
          - make
          - export ASAN_OPTIONS=detect_leaks=0
          - make test TEST_VERBOSE=1
      - language: shell
        os:
          - windows
        before_install:
          - choco install strawberryperl
        script:
          - perl Makefile.PL verbose
          - cmake
          - cmake test TEST_VERBOSE=1
